[2024-07-30T14:39:22.811+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T14:39:22.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_stock_data.get_data scheduled__2024-07-30T14:30:00+00:00 [queued]>
[2024-07-30T14:39:22.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_stock_data.get_data scheduled__2024-07-30T14:30:00+00:00 [queued]>
[2024-07-30T14:39:22.870+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-30T14:39:22.892+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-07-30 14:30:00+00:00
[2024-07-30T14:39:22.904+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-30T14:39:22.906+0000] {standard_task_runner.py:64} INFO - Started process 335 to run task
[2024-07-30T14:39:22.902+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'send_stock_data', 'get_data', 'scheduled__2024-07-30T14:30:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/***_stream.py', '--cfg-path', '/tmp/tmpc5bhf_uf']
[2024-07-30T14:39:22.908+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask get_data
[2024-07-30T14:39:22.930+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-30T14:39:22.981+0000] {task_command.py:426} INFO - Running <TaskInstance: send_stock_data.get_data scheduled__2024-07-30T14:30:00+00:00 [running]> on host da3e94a6f80e
[2024-07-30T14:39:23.129+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_stock_data' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T14:30:00+00:00'
[2024-07-30T14:39:23.131+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T14:39:23.188+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T14:39:23.189+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_data() missing 1 required positional argument: 'symbols'
[2024-07-30T14:39:23.203+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=send_stock_data, task_id=get_data, run_id=scheduled__2024-07-30T14:30:00+00:00, execution_date=20240730T143000, start_date=20240730T143922, end_date=20240730T143923
[2024-07-30T14:39:23.225+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task get_data (get_data() missing 1 required positional argument: 'symbols'; 335)
[2024-07-30T14:39:23.242+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-30T14:39:23.283+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T14:39:23.290+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
